variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
  CASSANDRA_HOST: cassandra

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .stack

services:
  - cassandra:3.11.2

before_script:
  - apt -qq update

test:8.4:
  image: haskell:8.4
  script:
    - apt -qq install build-essential libssl-dev > /dev/null
    - stack clean --full
    - stack -j 1 --resolver nightly-2018-06-19 test --fast

test:8.2:
  image: haskell:8.2
  script:
    - apt -qq install build-essential libssl-dev > /dev/null
    - stack clean --full
    - stack -j 1 test --fast

test:8.0:
  image: haskell:8.0
  script:
    - apt -qq install build-essential netbase xz-utils libstdc++-4.9-dev libssl-dev > /dev/null
    - stack upgrade && hash -d stack && stack --version
    - stack clean --full
    - stack -j 1 --resolver lts-9.21 test --fast

